version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: cr.yandex/crpp8odc6temeugiivj2/todo-registry/todo-backend:${VERSION}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tododb
      - SPRING_DATASOURCE_USERNAME=todo_user
      - SPRING_DATASOURCE_PASSWORD=todo_password
    ports:
      - "8081:8080"

  frontend:
    image: cr.yandex/crpp8odc6temeugiivj2/todo-registry/todo-frontend:${VERSION}
    environment:
      - REACT_APP_API_URL=http://backend:8081
    ports:
      - "80:80"

volumes:
  db-data:

