version: "3.8"

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: cr.yandex/crprmuig7ls6e7kr82qn/todo-registry/todo-backend:22
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tododb
      SPRING_DATASOURCE_USERNAME: todo_user
      SPRING_DATASOURCE_PASSWORD: todo_password
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    image: cr.yandex/crprmuig7ls6e7kr82qn/todo-registry/todo-frontend:22
    container_name: frontend
    environment:
      REACT_APP_API_URL: http://backend:8080
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db-data:
