version: "3"

services:
  backend:
    image: cr.yandex/<registry_id>/todo-registry/todo-backend:v1
    ports:
      - "8080:8080"
    # backend будет доступен по имени "backend" в сети docker

  frontend:
    image: cr.yandex/<registry_id>/todo-registry/todo-frontend:v1
    ports:
      - "80:80"
    # Предположим, ваш фронтенд код настраивается через переменные окружения,
    # чтобы обратиться к бекенду не по localhost, а по имени "backend".
    # Если в коде фронтенда есть возможность указать адрес API через env,
    # передайте env-переменную:
    environment:
      - REACT_APP_API_URL=http://backend:8080
    depends_on:
      - backend
