apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: todo_password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/tododb
            - name: SPRING_DATASOURCE_USERNAME
              value: todo_user
          image: cr.yandex/crpp8odc6temeugiivj2/todo-registry/todo-backend:latest
          name: backend
          ports:
            - containerPort: 8080
          resources: {}
      imagePullSecrets:
        - name: ycr-auth
      restartPolicy: Always

