apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: REACT_APP_API_URL
              value: http://backend:8081/tasks
          image: cr.yandex/crpp8odc6temeugiivj2/todo-registry/todo-frontend:latest
          name: frontend
          ports:
            - containerPort: 80
          resources: {}
      imagePullSecrets:
        - name: ycr-auth
      restartPolicy: Always
status: {}

